// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: inv.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvReq) Reset() {
	*x = InvReq{}
	mi := &file_inv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvReq) ProtoMessage() {}

func (x *InvReq) ProtoReflect() protoreflect.Message {
	mi := &file_inv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvReq.ProtoReflect.Descriptor instead.
func (*InvReq) Descriptor() ([]byte, []int) {
	return file_inv_proto_rawDescGZIP(), []int{0}
}

type InvRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invs          []*Inv                 `protobuf:"bytes,1,rep,name=invs,proto3" json:"invs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvRet) Reset() {
	*x = InvRet{}
	mi := &file_inv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvRet) ProtoMessage() {}

func (x *InvRet) ProtoReflect() protoreflect.Message {
	mi := &file_inv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvRet.ProtoReflect.Descriptor instead.
func (*InvRet) Descriptor() ([]byte, []int) {
	return file_inv_proto_rawDescGZIP(), []int{1}
}

func (x *InvRet) GetInvs() []*Inv {
	if x != nil {
		return x.Invs
	}
	return nil
}

type Inv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inv) Reset() {
	*x = Inv{}
	mi := &file_inv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inv) ProtoMessage() {}

func (x *Inv) ProtoReflect() protoreflect.Message {
	mi := &file_inv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inv.ProtoReflect.Descriptor instead.
func (*Inv) Descriptor() ([]byte, []int) {
	return file_inv_proto_rawDescGZIP(), []int{2}
}

func (x *Inv) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Inv) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_inv_proto protoreflect.FileDescriptor

var file_inv_proto_rawDesc = []byte{
	0x0a, 0x09, 0x69, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63,
	0x22, 0x08, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x22, 0x26, 0x0a, 0x06, 0x49, 0x6e,
	0x76, 0x52, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x69, 0x6e, 0x76, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x76, 0x52, 0x04, 0x69, 0x6e,
	0x76, 0x73, 0x22, 0x2d, 0x0a, 0x03, 0x49, 0x6e, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x32, 0x2c, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x53, 0x72, 0x76, 0x12, 0x22, 0x0a, 0x06, 0x52,
	0x65, 0x71, 0x49, 0x6e, 0x76, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x76, 0x52,
	0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x76, 0x52, 0x65, 0x74, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inv_proto_rawDescOnce sync.Once
	file_inv_proto_rawDescData = file_inv_proto_rawDesc
)

func file_inv_proto_rawDescGZIP() []byte {
	file_inv_proto_rawDescOnce.Do(func() {
		file_inv_proto_rawDescData = protoimpl.X.CompressGZIP(file_inv_proto_rawDescData)
	})
	return file_inv_proto_rawDescData
}

var file_inv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inv_proto_goTypes = []any{
	(*InvReq)(nil), // 0: rpc.InvReq
	(*InvRet)(nil), // 1: rpc.InvRet
	(*Inv)(nil),    // 2: rpc.Inv
}
var file_inv_proto_depIdxs = []int32{
	2, // 0: rpc.InvRet.invs:type_name -> rpc.Inv
	0, // 1: rpc.InvSrv.ReqInv:input_type -> rpc.InvReq
	1, // 2: rpc.InvSrv.ReqInv:output_type -> rpc.InvRet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inv_proto_init() }
func file_inv_proto_init() {
	if File_inv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inv_proto_goTypes,
		DependencyIndexes: file_inv_proto_depIdxs,
		MessageInfos:      file_inv_proto_msgTypes,
	}.Build()
	File_inv_proto = out.File
	file_inv_proto_rawDesc = nil
	file_inv_proto_goTypes = nil
	file_inv_proto_depIdxs = nil
}
