// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: inv.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvSrv_ReqInv_FullMethodName = "/rpc.InvSrv/ReqInv"
)

// InvSrvClient is the client API for InvSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvSrvClient interface {
	ReqInv(ctx context.Context, in *InvReq, opts ...grpc.CallOption) (*InvRet, error)
}

type invSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewInvSrvClient(cc grpc.ClientConnInterface) InvSrvClient {
	return &invSrvClient{cc}
}

func (c *invSrvClient) ReqInv(ctx context.Context, in *InvReq, opts ...grpc.CallOption) (*InvRet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvRet)
	err := c.cc.Invoke(ctx, InvSrv_ReqInv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvSrvServer is the server API for InvSrv service.
// All implementations must embed UnimplementedInvSrvServer
// for forward compatibility.
type InvSrvServer interface {
	ReqInv(context.Context, *InvReq) (*InvRet, error)
	mustEmbedUnimplementedInvSrvServer()
}

// UnimplementedInvSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvSrvServer struct{}

func (UnimplementedInvSrvServer) ReqInv(context.Context, *InvReq) (*InvRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqInv not implemented")
}
func (UnimplementedInvSrvServer) mustEmbedUnimplementedInvSrvServer() {}
func (UnimplementedInvSrvServer) testEmbeddedByValue()                {}

// UnsafeInvSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvSrvServer will
// result in compilation errors.
type UnsafeInvSrvServer interface {
	mustEmbedUnimplementedInvSrvServer()
}

func RegisterInvSrvServer(s grpc.ServiceRegistrar, srv InvSrvServer) {
	// If the following call pancis, it indicates UnimplementedInvSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvSrv_ServiceDesc, srv)
}

func _InvSrv_ReqInv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvSrvServer).ReqInv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvSrv_ReqInv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvSrvServer).ReqInv(ctx, req.(*InvReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InvSrv_ServiceDesc is the grpc.ServiceDesc for InvSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.InvSrv",
	HandlerType: (*InvSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqInv",
			Handler:    _InvSrv_ReqInv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inv.proto",
}
