// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: vers.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	BestHeight    int64                  `protobuf:"varint,2,opt,name=BestHeight,proto3" json:"BestHeight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersReq) Reset() {
	*x = VersReq{}
	mi := &file_vers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersReq) ProtoMessage() {}

func (x *VersReq) ProtoReflect() protoreflect.Message {
	mi := &file_vers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersReq.ProtoReflect.Descriptor instead.
func (*VersReq) Descriptor() ([]byte, []int) {
	return file_vers_proto_rawDescGZIP(), []int{0}
}

func (x *VersReq) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersReq) GetBestHeight() int64 {
	if x != nil {
		return x.BestHeight
	}
	return 0
}

type VersRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	BestHeight    int64                  `protobuf:"varint,2,opt,name=BestHeight,proto3" json:"BestHeight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersRet) Reset() {
	*x = VersRet{}
	mi := &file_vers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersRet) ProtoMessage() {}

func (x *VersRet) ProtoReflect() protoreflect.Message {
	mi := &file_vers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersRet.ProtoReflect.Descriptor instead.
func (*VersRet) Descriptor() ([]byte, []int) {
	return file_vers_proto_rawDescGZIP(), []int{1}
}

func (x *VersRet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersRet) GetBestHeight() int64 {
	if x != nil {
		return x.BestHeight
	}
	return 0
}

var File_vers_proto protoreflect.FileDescriptor

var file_vers_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70,
	0x63, 0x22, 0x43, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x65, 0x73, 0x74, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x42, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x43, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x65, 0x73, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x42, 0x65, 0x73, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0x30, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x53, 0x72, 0x76, 0x12, 0x25, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x56, 0x65, 0x72,
	0x73, 0x12, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x74, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vers_proto_rawDescOnce sync.Once
	file_vers_proto_rawDescData = file_vers_proto_rawDesc
)

func file_vers_proto_rawDescGZIP() []byte {
	file_vers_proto_rawDescOnce.Do(func() {
		file_vers_proto_rawDescData = protoimpl.X.CompressGZIP(file_vers_proto_rawDescData)
	})
	return file_vers_proto_rawDescData
}

var file_vers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vers_proto_goTypes = []any{
	(*VersReq)(nil), // 0: rpc.versReq
	(*VersRet)(nil), // 1: rpc.versRet
}
var file_vers_proto_depIdxs = []int32{
	0, // 0: rpc.versSrv.ReqVers:input_type -> rpc.versReq
	1, // 1: rpc.versSrv.ReqVers:output_type -> rpc.versRet
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vers_proto_init() }
func file_vers_proto_init() {
	if File_vers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vers_proto_goTypes,
		DependencyIndexes: file_vers_proto_depIdxs,
		MessageInfos:      file_vers_proto_msgTypes,
	}.Build()
	File_vers_proto = out.File
	file_vers_proto_rawDesc = nil
	file_vers_proto_goTypes = nil
	file_vers_proto_depIdxs = nil
}
