// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: blk.proto

package global

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          [][]byte               `protobuf:"bytes,1,rep,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlkReq) Reset() {
	*x = BlkReq{}
	mi := &file_blk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlkReq) ProtoMessage() {}

func (x *BlkReq) ProtoReflect() protoreflect.Message {
	mi := &file_blk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlkReq.ProtoReflect.Descriptor instead.
func (*BlkReq) Descriptor() ([]byte, []int) {
	return file_blk_proto_rawDescGZIP(), []int{0}
}

func (x *BlkReq) GetHash() [][]byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Blk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txs           []*Tx                  `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	PrevBlkHash   []byte                 `protobuf:"bytes,3,opt,name=PrevBlkHash,proto3" json:"PrevBlkHash,omitempty"`
	Hash          []byte                 `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Nonce         int64                  `protobuf:"varint,5,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Height        int64                  `protobuf:"varint,6,opt,name=Height,proto3" json:"Height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blk) Reset() {
	*x = Blk{}
	mi := &file_blk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blk) ProtoMessage() {}

func (x *Blk) ProtoReflect() protoreflect.Message {
	mi := &file_blk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blk.ProtoReflect.Descriptor instead.
func (*Blk) Descriptor() ([]byte, []int) {
	return file_blk_proto_rawDescGZIP(), []int{1}
}

func (x *Blk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Blk) GetTxs() []*Tx {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *Blk) GetPrevBlkHash() []byte {
	if x != nil {
		return x.PrevBlkHash
	}
	return nil
}

func (x *Blk) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Blk) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Blk) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_blk_proto protoreflect.FileDescriptor

var file_blk_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x6c, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x1a, 0x08, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x06, 0x42,
	0x6c, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xa5, 0x01, 0x0a, 0x03, 0x42, 0x6c,
	0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x1c, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x54, 0x78, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x72, 0x65, 0x76, 0x42, 0x6c, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x50, 0x72, 0x65, 0x76, 0x42, 0x6c, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x32, 0x56, 0x0a, 0x06, 0x42, 0x6c, 0x6b, 0x53, 0x72, 0x76, 0x12, 0x27, 0x0a, 0x06, 0x52,
	0x65, 0x71, 0x42, 0x6c, 0x6b, 0x12, 0x0e, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x42,
	0x6c, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x42,
	0x6c, 0x6b, 0x30, 0x01, 0x12, 0x23, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6b, 0x12,
	0x0b, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x42, 0x6c, 0x6b, 0x1a, 0x0b, 0x2e, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x41, 0x63, 0x6b, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blk_proto_rawDescOnce sync.Once
	file_blk_proto_rawDescData = file_blk_proto_rawDesc
)

func file_blk_proto_rawDescGZIP() []byte {
	file_blk_proto_rawDescOnce.Do(func() {
		file_blk_proto_rawDescData = protoimpl.X.CompressGZIP(file_blk_proto_rawDescData)
	})
	return file_blk_proto_rawDescData
}

var file_blk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blk_proto_goTypes = []any{
	(*BlkReq)(nil), // 0: global.BlkReq
	(*Blk)(nil),    // 1: global.Blk
	(*Tx)(nil),     // 2: global.Tx
	(*Ack)(nil),    // 3: global.Ack
}
var file_blk_proto_depIdxs = []int32{
	2, // 0: global.Blk.txs:type_name -> global.Tx
	0, // 1: global.BlkSrv.ReqBlk:input_type -> global.BlkReq
	1, // 2: global.BlkSrv.SendBlk:input_type -> global.Blk
	1, // 3: global.BlkSrv.ReqBlk:output_type -> global.Blk
	3, // 4: global.BlkSrv.SendBlk:output_type -> global.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blk_proto_init() }
func file_blk_proto_init() {
	if File_blk_proto != nil {
		return
	}
	file_tx_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blk_proto_goTypes,
		DependencyIndexes: file_blk_proto_depIdxs,
		MessageInfos:      file_blk_proto_msgTypes,
	}.Build()
	File_blk_proto = out.File
	file_blk_proto_rawDesc = nil
	file_blk_proto_goTypes = nil
	file_blk_proto_depIdxs = nil
}
