// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: global/inv.proto

package global

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvType int32

const (
	InvType_BlkInv InvType = 0
	InvType_TxInv  InvType = 1
)

// Enum value maps for InvType.
var (
	InvType_name = map[int32]string{
		0: "BlkInv",
		1: "TxInv",
	}
	InvType_value = map[string]int32{
		"BlkInv": 0,
		"TxInv":  1,
	}
)

func (x InvType) Enum() *InvType {
	p := new(InvType)
	*p = x
	return p
}

func (x InvType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvType) Descriptor() protoreflect.EnumDescriptor {
	return file_global_inv_proto_enumTypes[0].Descriptor()
}

func (InvType) Type() protoreflect.EnumType {
	return &file_global_inv_proto_enumTypes[0]
}

func (x InvType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvType.Descriptor instead.
func (InvType) EnumDescriptor() ([]byte, []int) {
	return file_global_inv_proto_rawDescGZIP(), []int{0}
}

type InvReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvReq) Reset() {
	*x = InvReq{}
	mi := &file_global_inv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvReq) ProtoMessage() {}

func (x *InvReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_inv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvReq.ProtoReflect.Descriptor instead.
func (*InvReq) Descriptor() ([]byte, []int) {
	return file_global_inv_proto_rawDescGZIP(), []int{0}
}

type InvRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invs          []*Inv                 `protobuf:"bytes,1,rep,name=invs,proto3" json:"invs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvRet) Reset() {
	*x = InvRet{}
	mi := &file_global_inv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvRet) ProtoMessage() {}

func (x *InvRet) ProtoReflect() protoreflect.Message {
	mi := &file_global_inv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvRet.ProtoReflect.Descriptor instead.
func (*InvRet) Descriptor() ([]byte, []int) {
	return file_global_inv_proto_rawDescGZIP(), []int{1}
}

func (x *InvRet) GetInvs() []*Inv {
	if x != nil {
		return x.Invs
	}
	return nil
}

type Inv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          InvType                `protobuf:"varint,1,opt,name=type,proto3,enum=global.InvType" json:"type,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inv) Reset() {
	*x = Inv{}
	mi := &file_global_inv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inv) ProtoMessage() {}

func (x *Inv) ProtoReflect() protoreflect.Message {
	mi := &file_global_inv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inv.ProtoReflect.Descriptor instead.
func (*Inv) Descriptor() ([]byte, []int) {
	return file_global_inv_proto_rawDescGZIP(), []int{2}
}

func (x *Inv) GetType() InvType {
	if x != nil {
		return x.Type
	}
	return InvType_BlkInv
}

func (x *Inv) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_global_inv_proto protoreflect.FileDescriptor

var file_global_inv_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x22, 0x08, 0x0a, 0x06, 0x49, 0x6e,
	0x76, 0x52, 0x65, 0x71, 0x22, 0x29, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x52, 0x65, 0x74, 0x12, 0x1f,
	0x0a, 0x04, 0x69, 0x6e, 0x76, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x49, 0x6e, 0x76, 0x52, 0x04, 0x69, 0x6e, 0x76, 0x73, 0x22,
	0x3e, 0x0a, 0x03, 0x49, 0x6e, 0x76, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x49, 0x6e,
	0x76, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x2a,
	0x20, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x6c,
	0x6b, 0x49, 0x6e, 0x76, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x78, 0x49, 0x6e, 0x76, 0x10,
	0x01, 0x32, 0x32, 0x0a, 0x06, 0x49, 0x6e, 0x76, 0x53, 0x72, 0x76, 0x12, 0x28, 0x0a, 0x06, 0x52,
	0x65, 0x71, 0x49, 0x6e, 0x76, 0x12, 0x0e, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x49,
	0x6e, 0x76, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x49,
	0x6e, 0x76, 0x52, 0x65, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x73, 0x68, 0x74, 0x61, 0x72, 0x31, 0x33, 0x2f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_inv_proto_rawDescOnce sync.Once
	file_global_inv_proto_rawDescData = file_global_inv_proto_rawDesc
)

func file_global_inv_proto_rawDescGZIP() []byte {
	file_global_inv_proto_rawDescOnce.Do(func() {
		file_global_inv_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_inv_proto_rawDescData)
	})
	return file_global_inv_proto_rawDescData
}

var file_global_inv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_global_inv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_global_inv_proto_goTypes = []any{
	(InvType)(0),   // 0: global.InvType
	(*InvReq)(nil), // 1: global.InvReq
	(*InvRet)(nil), // 2: global.InvRet
	(*Inv)(nil),    // 3: global.Inv
}
var file_global_inv_proto_depIdxs = []int32{
	3, // 0: global.InvRet.invs:type_name -> global.Inv
	0, // 1: global.Inv.type:type_name -> global.InvType
	1, // 2: global.InvSrv.ReqInv:input_type -> global.InvReq
	2, // 3: global.InvSrv.ReqInv:output_type -> global.InvRet
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_global_inv_proto_init() }
func file_global_inv_proto_init() {
	if File_global_inv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_inv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_global_inv_proto_goTypes,
		DependencyIndexes: file_global_inv_proto_depIdxs,
		EnumInfos:         file_global_inv_proto_enumTypes,
		MessageInfos:      file_global_inv_proto_msgTypes,
	}.Build()
	File_global_inv_proto = out.File
	file_global_inv_proto_rawDesc = nil
	file_global_inv_proto_goTypes = nil
	file_global_inv_proto_depIdxs = nil
}
