// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: global/ledger.proto

package global

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_Central NodeType = 0
	NodeType_Miner   NodeType = 1
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "Central",
		1: "Miner",
	}
	NodeType_value = map[string]int32{
		"Central": 0,
		"Miner":   1,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_global_ledger_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_global_ledger_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_global_ledger_proto_rawDescGZIP(), []int{0}
}

type NodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NodeType               `protobuf:"varint,1,opt,name=Type,proto3,enum=global.NodeType" json:"Type,omitempty"`
	Nodes         map[string]bool        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeReq) Reset() {
	*x = NodeReq{}
	mi := &file_global_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReq) ProtoMessage() {}

func (x *NodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReq.ProtoReflect.Descriptor instead.
func (*NodeReq) Descriptor() ([]byte, []int) {
	return file_global_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *NodeReq) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_Central
}

func (x *NodeReq) GetNodes() map[string]bool {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeRet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRet) Reset() {
	*x = NodeRet{}
	mi := &file_global_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRet) ProtoMessage() {}

func (x *NodeRet) ProtoReflect() protoreflect.Message {
	mi := &file_global_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRet.ProtoReflect.Descriptor instead.
func (*NodeRet) Descriptor() ([]byte, []int) {
	return file_global_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRet) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_global_ledger_proto protoreflect.FileDescriptor

var file_global_ledger_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x22, 0x9b, 0x01,
	0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x30, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1f, 0x0a, 0x07, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2a, 0x22, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x65, 0x6e, 0x74,
	0x72, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x10, 0x01,
	0x32, 0x39, 0x0a, 0x09, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x53, 0x72, 0x76, 0x12, 0x2c, 0x0a,
	0x08, 0x52, 0x65, 0x71, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x0f, 0x2e, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x67, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x74, 0x42, 0x2c, 0x5a, 0x2a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x73, 0x68, 0x74, 0x61, 0x72,
	0x31, 0x33, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x6f,
	0x64, 0x65, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_global_ledger_proto_rawDescOnce sync.Once
	file_global_ledger_proto_rawDescData = file_global_ledger_proto_rawDesc
)

func file_global_ledger_proto_rawDescGZIP() []byte {
	file_global_ledger_proto_rawDescOnce.Do(func() {
		file_global_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_ledger_proto_rawDescData)
	})
	return file_global_ledger_proto_rawDescData
}

var file_global_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_global_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_global_ledger_proto_goTypes = []any{
	(NodeType)(0),   // 0: global.NodeType
	(*NodeReq)(nil), // 1: global.NodeReq
	(*NodeRet)(nil), // 2: global.NodeRet
	nil,             // 3: global.NodeReq.NodesEntry
}
var file_global_ledger_proto_depIdxs = []int32{
	0, // 0: global.NodeReq.Type:type_name -> global.NodeType
	3, // 1: global.NodeReq.nodes:type_name -> global.NodeReq.NodesEntry
	1, // 2: global.LedgerSrv.ReqNodes:input_type -> global.NodeReq
	2, // 3: global.LedgerSrv.ReqNodes:output_type -> global.NodeRet
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_global_ledger_proto_init() }
func file_global_ledger_proto_init() {
	if File_global_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_ledger_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_global_ledger_proto_goTypes,
		DependencyIndexes: file_global_ledger_proto_depIdxs,
		EnumInfos:         file_global_ledger_proto_enumTypes,
		MessageInfos:      file_global_ledger_proto_msgTypes,
	}.Build()
	File_global_ledger_proto = out.File
	file_global_ledger_proto_rawDesc = nil
	file_global_ledger_proto_goTypes = nil
	file_global_ledger_proto_depIdxs = nil
}
