// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: global/ledger.proto

package global

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerSrv_ReqNodes_FullMethodName = "/global.LedgerSrv/ReqNodes"
)

// LedgerSrvClient is the client API for LedgerSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerSrvClient interface {
	ReqNodes(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRet, error)
}

type ledgerSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerSrvClient(cc grpc.ClientConnInterface) LedgerSrvClient {
	return &ledgerSrvClient{cc}
}

func (c *ledgerSrvClient) ReqNodes(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRet)
	err := c.cc.Invoke(ctx, LedgerSrv_ReqNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerSrvServer is the server API for LedgerSrv service.
// All implementations must embed UnimplementedLedgerSrvServer
// for forward compatibility.
type LedgerSrvServer interface {
	ReqNodes(context.Context, *NodeReq) (*NodeRet, error)
	mustEmbedUnimplementedLedgerSrvServer()
}

// UnimplementedLedgerSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerSrvServer struct{}

func (UnimplementedLedgerSrvServer) ReqNodes(context.Context, *NodeReq) (*NodeRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqNodes not implemented")
}
func (UnimplementedLedgerSrvServer) mustEmbedUnimplementedLedgerSrvServer() {}
func (UnimplementedLedgerSrvServer) testEmbeddedByValue()                   {}

// UnsafeLedgerSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerSrvServer will
// result in compilation errors.
type UnsafeLedgerSrvServer interface {
	mustEmbedUnimplementedLedgerSrvServer()
}

func RegisterLedgerSrvServer(s grpc.ServiceRegistrar, srv LedgerSrvServer) {
	// If the following call pancis, it indicates UnimplementedLedgerSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerSrv_ServiceDesc, srv)
}

func _LedgerSrv_ReqNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerSrvServer).ReqNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerSrv_ReqNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerSrvServer).ReqNodes(ctx, req.(*NodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerSrv_ServiceDesc is the grpc.ServiceDesc for LedgerSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "global.LedgerSrv",
	HandlerType: (*LedgerSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqNodes",
			Handler:    _LedgerSrv_ReqNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "global/ledger.proto",
}
