// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: global/tx.proto

package global

import (
	protos "github.com/lshtar13/blockchain/node/protos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          [][]byte               `protobuf:"bytes,1,rep,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxReq) Reset() {
	*x = TxReq{}
	mi := &file_global_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxReq) ProtoMessage() {}

func (x *TxReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxReq.ProtoReflect.Descriptor instead.
func (*TxReq) Descriptor() ([]byte, []int) {
	return file_global_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxReq) GetHash() [][]byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_global_tx_proto protoreflect.FileDescriptor

var file_global_tx_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a,
	0x05, 0x54, 0x78, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x32, 0x50, 0x0a, 0x05, 0x54, 0x78,
	0x53, 0x72, 0x76, 0x12, 0x24, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x54, 0x78, 0x12, 0x0d, 0x2e, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x78, 0x30, 0x01, 0x12, 0x21, 0x0a, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x78, 0x12, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x78, 0x1a,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x63, 0x6b, 0x42, 0x2c, 0x5a, 0x2a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x73, 0x68, 0x74, 0x61,
	0x72, 0x31, 0x33, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6e,
	0x6f, 0x64, 0x65, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_global_tx_proto_rawDescOnce sync.Once
	file_global_tx_proto_rawDescData = file_global_tx_proto_rawDesc
)

func file_global_tx_proto_rawDescGZIP() []byte {
	file_global_tx_proto_rawDescOnce.Do(func() {
		file_global_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_tx_proto_rawDescData)
	})
	return file_global_tx_proto_rawDescData
}

var file_global_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_global_tx_proto_goTypes = []any{
	(*TxReq)(nil),      // 0: global.TxReq
	(*protos.Tx)(nil),  // 1: protos.Tx
	(*protos.Ack)(nil), // 2: protos.Ack
}
var file_global_tx_proto_depIdxs = []int32{
	0, // 0: global.TxSrv.ReqTx:input_type -> global.TxReq
	1, // 1: global.TxSrv.SendTx:input_type -> protos.Tx
	1, // 2: global.TxSrv.ReqTx:output_type -> protos.Tx
	2, // 3: global.TxSrv.SendTx:output_type -> protos.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_global_tx_proto_init() }
func file_global_tx_proto_init() {
	if File_global_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_global_tx_proto_goTypes,
		DependencyIndexes: file_global_tx_proto_depIdxs,
		MessageInfos:      file_global_tx_proto_msgTypes,
	}.Build()
	File_global_tx_proto = out.File
	file_global_tx_proto_rawDesc = nil
	file_global_tx_proto_goTypes = nil
	file_global_tx_proto_depIdxs = nil
}
