// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: global/tx.proto

package global

import (
	context "context"
	protos "github.com/lshtar13/blockchain/node/protos"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TxSrv_ReqTx_FullMethodName  = "/global.TxSrv/ReqTx"
	TxSrv_SendTx_FullMethodName = "/global.TxSrv/SendTx"
)

// TxSrvClient is the client API for TxSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TxSrvClient interface {
	ReqTx(ctx context.Context, in *TxReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.Tx], error)
	SendTx(ctx context.Context, in *protos.Tx, opts ...grpc.CallOption) (*protos.Ack, error)
}

type txSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewTxSrvClient(cc grpc.ClientConnInterface) TxSrvClient {
	return &txSrvClient{cc}
}

func (c *txSrvClient) ReqTx(ctx context.Context, in *TxReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[protos.Tx], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TxSrv_ServiceDesc.Streams[0], TxSrv_ReqTx_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TxReq, protos.Tx]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxSrv_ReqTxClient = grpc.ServerStreamingClient[protos.Tx]

func (c *txSrvClient) SendTx(ctx context.Context, in *protos.Tx, opts ...grpc.CallOption) (*protos.Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(protos.Ack)
	err := c.cc.Invoke(ctx, TxSrv_SendTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxSrvServer is the server API for TxSrv service.
// All implementations must embed UnimplementedTxSrvServer
// for forward compatibility.
type TxSrvServer interface {
	ReqTx(*TxReq, grpc.ServerStreamingServer[protos.Tx]) error
	SendTx(context.Context, *protos.Tx) (*protos.Ack, error)
	mustEmbedUnimplementedTxSrvServer()
}

// UnimplementedTxSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTxSrvServer struct{}

func (UnimplementedTxSrvServer) ReqTx(*TxReq, grpc.ServerStreamingServer[protos.Tx]) error {
	return status.Errorf(codes.Unimplemented, "method ReqTx not implemented")
}
func (UnimplementedTxSrvServer) SendTx(context.Context, *protos.Tx) (*protos.Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTx not implemented")
}
func (UnimplementedTxSrvServer) mustEmbedUnimplementedTxSrvServer() {}
func (UnimplementedTxSrvServer) testEmbeddedByValue()               {}

// UnsafeTxSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TxSrvServer will
// result in compilation errors.
type UnsafeTxSrvServer interface {
	mustEmbedUnimplementedTxSrvServer()
}

func RegisterTxSrvServer(s grpc.ServiceRegistrar, srv TxSrvServer) {
	// If the following call pancis, it indicates UnimplementedTxSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TxSrv_ServiceDesc, srv)
}

func _TxSrv_ReqTx_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TxReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TxSrvServer).ReqTx(m, &grpc.GenericServerStream[TxReq, protos.Tx]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TxSrv_ReqTxServer = grpc.ServerStreamingServer[protos.Tx]

func _TxSrv_SendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protos.Tx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxSrvServer).SendTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TxSrv_SendTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxSrvServer).SendTx(ctx, req.(*protos.Tx))
	}
	return interceptor(ctx, in, info, handler)
}

// TxSrv_ServiceDesc is the grpc.ServiceDesc for TxSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TxSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "global.TxSrv",
	HandlerType: (*TxSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTx",
			Handler:    _TxSrv_SendTx_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReqTx",
			Handler:       _TxSrv_ReqTx_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "global/tx.proto",
}
