// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: local/UTXO.proto

package local

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UTXOSrv_ReqBalance_FullMethodName = "/local.UTXOSrv/ReqBalance"
)

// UTXOSrvClient is the client API for UTXOSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UTXOSrvClient interface {
	ReqBalance(ctx context.Context, in *BalanceReq, opts ...grpc.CallOption) (*Balance, error)
}

type uTXOSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewUTXOSrvClient(cc grpc.ClientConnInterface) UTXOSrvClient {
	return &uTXOSrvClient{cc}
}

func (c *uTXOSrvClient) ReqBalance(ctx context.Context, in *BalanceReq, opts ...grpc.CallOption) (*Balance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Balance)
	err := c.cc.Invoke(ctx, UTXOSrv_ReqBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UTXOSrvServer is the server API for UTXOSrv service.
// All implementations must embed UnimplementedUTXOSrvServer
// for forward compatibility.
type UTXOSrvServer interface {
	ReqBalance(context.Context, *BalanceReq) (*Balance, error)
	mustEmbedUnimplementedUTXOSrvServer()
}

// UnimplementedUTXOSrvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUTXOSrvServer struct{}

func (UnimplementedUTXOSrvServer) ReqBalance(context.Context, *BalanceReq) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqBalance not implemented")
}
func (UnimplementedUTXOSrvServer) mustEmbedUnimplementedUTXOSrvServer() {}
func (UnimplementedUTXOSrvServer) testEmbeddedByValue()                 {}

// UnsafeUTXOSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UTXOSrvServer will
// result in compilation errors.
type UnsafeUTXOSrvServer interface {
	mustEmbedUnimplementedUTXOSrvServer()
}

func RegisterUTXOSrvServer(s grpc.ServiceRegistrar, srv UTXOSrvServer) {
	// If the following call pancis, it indicates UnimplementedUTXOSrvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UTXOSrv_ServiceDesc, srv)
}

func _UTXOSrv_ReqBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UTXOSrvServer).ReqBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UTXOSrv_ReqBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UTXOSrvServer).ReqBalance(ctx, req.(*BalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UTXOSrv_ServiceDesc is the grpc.ServiceDesc for UTXOSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UTXOSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "local.UTXOSrv",
	HandlerType: (*UTXOSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqBalance",
			Handler:    _UTXOSrv_ReqBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "local/UTXO.proto",
}
